### ISSUE TITLE
Option --definition doesn't work

### ISSUE THREAD

**Issue by ladyga14** [mpolidori/python-oxd#6]
It's weird that synonyms work well while definition always output "No matches found". Of course, I test with the same word.

**Comment by mpolidori** [comment]
Thanks for flagging this! They had changed the URL format a while back, and it looks like I pushed the fix for synonyms and not definitions. I'm pushing the fix now.

**Comment by mpolidori** [comment]
Let me know if you have any other issues. Thanks for trying it out!
